import { School, Question, Exam, AdminUser } from '../types';

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'sch-1',
    name: 'SMPN 3 Pacet',
    npsn: '20502781',
    address: 'Jl. Raya Pacet Selatan, Mojokerto',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sch-2',
    name: 'SMPN 1 Puri',
    npsn: '20502755',
    address: 'Jl. Jayanegara No. 1, Puri, Mojokerto',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sch-3',
    name: 'SMPN 2 Pacet',
    npsn: '20502780',
    address: 'Jl. Air Panas Padusan, Pacet, Mojokerto',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'q-001',
    subject: "Al-Qur'an Hadis",
    topic: 'Toleransi dan Menghargai Perbedaan',
    difficulty: 'Sedang',
    type: 'PG',
    stimulus: 'Perhatikan penggalan Q.S. Al-Hujurat [49]: 13 berikut ini:\n\nيٰٓاَيُّهَا النَّاسُ اِنَّا خَلَقْنٰكُمْ مِّنْ ذَكَرٍ وَّاُنْثٰى وَجَعَلْنٰكُمْ شُعُوْبًا وَّقَبَاۤىِٕلَ لِتَعَارَفُوْا ۚ اِنَّ اَكْرَمَكُمْ عِنْدَ اللّٰهِ اَتْقٰىكُمْ ۗ\n\nAyat ini menegaskan fitrah keberagaman manusia dari berbagai suku bangsa dan latar belakang budaya.',
    question: 'Berdasarkan ayat dan stimulus tersebut, prinsip utama hubungan sosial kemanusiaan dan ukuran kemuliaan seorang hamba di sisi Allah Swt. adalah....',
    options: [
      { id: 'A', text: 'Kekayaan materi dan tingginya kedudukan nasab keluarga' },
      { id: 'B', text: 'Saling mengenal (ta\'aruf) dan tingkat ketakwaan kepada Allah Swt.' },
      { id: 'C', text: 'Kekuatan fisik serta keunggulan suku mayoritas dalam masyarakat' },
      { id: 'D', text: 'Kemampuan menguasai sains dan dominasi politik' },
    ],
    correctAnswers: ['B'],
    explanation: 'Q.S. Al-Hujurat ayat 13 menjelaskan bahwa manusia diciptakan bersuku-suku dan berbangsa-bangsa agar saling mengenal (lita\'arafu) dan sesungguhnya orang yang paling mulia di sisi Allah adalah orang yang paling bertakwa.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-002',
    subject: 'Aqidah',
    topic: 'Iman Kepada Hari Akhir',
    difficulty: 'Sedang',
    type: 'PGK',
    stimulus: 'Hari Akhir adalah hari dihancurkannya alam semesta beserta isinya serta dimulainya kehidupan akhirat yang kekal. Setelah tiupan sangkakala kedua, manusia akan melalui tahapan-tahapan perhitungan amal.',
    question: 'Pilihlah DUA atau LEBIH tahapan peristiwa di yaumul akhir yang berkaitan langsung dengan pembalasan amal perbuatan manusia!',
    options: [
      { id: 'A', text: 'Yaumul Ba\'ats (Hari dibangkitkannya manusia dari alam kubur)' },
      { id: 'B', text: 'Yaumul Mizan (Hari penimbangan amal kebajikan dan keburukan)' },
      { id: 'C', text: 'Yaumul Hisab (Hari perhitungan amal perbuatan manusia secara terperinci)' },
      { id: 'D', text: 'Yaumul Milad (Hari peringatan kelahiran seorang rasul)' },
    ],
    correctAnswers: ['A', 'B', 'C'],
    explanation: 'Yaumul Ba\'ats, Yaumul Mizan, dan Yaumul Hisab adalah tahapan eskatologis di hari kiamat. Sedangkan Yaumul Milad artinya hari kelahiran dan bukan bagian dari tahapan hari akhir.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-003',
    subject: 'Fiqih',
    topic: 'Zakat Mal dan Ketentuannya',
    difficulty: 'Sukar',
    type: 'PG',
    stimulus: 'Pak Ahmad, seorang pedagang sukses di Mojosari Kabupaten Mojokerto, memiliki simpanan emas murni seberat 95 gram yang telah tersimpan genap selama satu tahun (haul). Harga emas saat itu adalah Rp1.000.000 per gram. Diketahui nisab emas adalah 85 gram dengan kadar zakat 2,5%.',
    question: 'Berapakah jumlah zakat mal yang wajib dikeluarkan oleh Pak Ahmad atas simpanan emas tersebut?',
    options: [
      { id: 'A', text: 'Rp 2.125.000' },
      { id: 'B', text: 'Rp 2.375.000' },
      { id: 'C', text: 'Rp 2.500.000' },
      { id: 'D', text: 'Rp 2.850.000' },
    ],
    correctAnswers: ['B'],
    explanation: 'Simpanan 95 gram sudah melebihi nisab 85 gram dan mencapai haul 1 tahun. Nilai total = 95 gram × Rp1.000.000 = Rp95.000.000. Zakat yang wajib dikeluarkan = 2,5% × Rp95.000.000 = Rp2.375.000.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-004',
    subject: 'Akhlak',
    topic: 'Sifat Terpuji (Adab Bergaul dan Tawadhu)',
    difficulty: 'Mudah',
    type: 'PG',
    stimulus: 'Fatimah adalah siswi SMP berprestasi yang sering menjuarai olimpiade sains dan PAI tingkat kabupaten. Meskipun memiliki segudang prestasi, ia tetap ramah, tidak pernah meremehkan teman sekelasnya, dan selalu bersedia membantu teman yang kesulitan memahami materi.',
    question: 'Sikap mulia yang ditunjukkan oleh Fatimah mencerminkan akhlakul karimah yaitu....',
    options: [
      { id: 'A', text: 'Tawadhu\' (rendah hati)' },
      { id: 'B', text: 'Qana\'ah (merasa cukup)' },
      { id: 'C', text: 'Raja\' (berharap rahmat Allah)' },
      { id: 'D', text: 'Tawakkal (berserah diri)' },
    ],
    correctAnswers: ['A'],
    explanation: 'Tawadhu\' artinya rendah hati, tidak sombong atau takabbur terhadap nikmat atau kelebihan ilmu dan prestasi yang dianugerahkan oleh Allah Swt.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-005',
    subject: 'Sejarah Kebudayaan Islam',
    topic: 'Perkembangan Peradaban Islam Daulah Abbasiyah',
    difficulty: 'Sedang',
    type: 'PGK',
    stimulus: 'Masa keemasan peradaban Islam (The Golden Age of Islam) tercapai pada era kekhalifahan Daulah Abbasiyah, khususnya pada masa pemerintahan Khalifah Harun Ar-Rasyid dan putranya Al-Ma\'mun di Baghdad.',
    question: 'Manakah dari pernyataan berikut yang merupakan wujud kemajuan peradaban ilmu pengetahuan pada masa Daulah Abbasiyah? (Pilih semua yang benar)',
    options: [
      { id: 'A', text: 'Didirikannya Baitul Hikmah sebagai pusat perpustakaan, observatorium, dan penerjemahan naskah ilmiah' },
      { id: 'B', text: 'Lahirnya ilmuwan besar Al-Khawarizmi yang menyusun karya dasar aljabar dan algoritma' },
      { id: 'C', text: 'Pembangunan Taj Mahal sebagai simbol keilmuan astronomi' },
      { id: 'D', text: 'Berkembang pesatnya studi kedokteran yang dipelopori ilmuwan Ibnu Sina (Avicenna)' },
    ],
    correctAnswers: ['A', 'B', 'D'],
    explanation: 'Baitul Hikmah, penemuan aljabar oleh Al-Khawarizmi, dan sumbangsih kedokteran Ibnu Sina adalah capaian era Abbasiyah. Taj Mahal dibangun pada abad ke-17 oleh Daulah Mughal di India.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-006',
    subject: "Al-Qur'an Hadis",
    topic: 'Hukum Bacaan Tajwid Mad dan Mim Mati',
    difficulty: 'Sedang',
    type: 'PG',
    stimulus: 'Dalam membaca Al-Qur\'an, ketepatan makharijul huruf dan tajwid sangat penting agar makna tidak berubah. Perhatikan lafal ayat berikut:\n\nفَمَنْ يَّعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَّرَهٗ\n\nPada lafal "فَمَنْ يَّعْمَلْ", terdapat huruf nun sukun (نْ) bertemu dengan huruf ya (ي).',
    question: 'Hukum tajwid yang terdapat pada lafal "فَمَنْ يَّعْمَلْ" adalah....',
    options: [
      { id: 'A', text: 'Idgham Bighunnah' },
      { id: 'B', text: 'Idgham Bilaghunnah' },
      { id: 'C', text: 'Iqlab' },
      { id: 'D', text: 'Ikhfa\' Haqiqi' },
    ],
    correctAnswers: ['A'],
    explanation: 'Nun sukun bertemu huruf Ya (ي) adalah Idgham Bighunnah (memasukkan bunyi nun ke dalam huruf sesudahnya dengan mendengung). Huruf Idgham Bighunnah ada 4: Ya, Nun, Mim, Waw (Yanmu).',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-007',
    subject: 'Fiqih',
    topic: 'Penyembelihan Hewan dan Qurban',
    difficulty: 'Sedang',
    type: 'PGK',
    stimulus: 'Ibadah qurban dilaksanakan setiap tanggal 10 Dzulhijjah dan hari Tasyrik. Agar ibadah qurban sah menurut syariat Islam, terdapat syarat-syarat khusus yang harus dipenuhi terkait hewan yang disembelih.',
    question: 'Pilihlah ketentuan dan syarat hewan qurban yang SAH menurut syariat Islam! (Pilih semua yang benar)',
    options: [
      { id: 'A', text: 'Merupakan hewan ternak (Bahimatul An\'am) seperti unta, sapi, kambing, atau domba' },
      { id: 'B', text: 'Telah mencapai batas umur minimal yang ditentukan (misal sapi minimal 2 tahun, kambing minimal 1 tahun)' },
      { id: 'C', text: 'Sehat, gemuk, dan bebas dari cacat fisik nyata seperti buta, pincang parah, atau sakit kurus kering' },
      { id: 'D', text: 'Boleh menggunakan ayam jantan kampung asalkan disembelih di hari Idul Adha' },
    ],
    correctAnswers: ['A', 'B', 'C'],
    explanation: 'Syarat hewan qurban adalah dari golongan Bahimatul An\'am (unta, sapi, kerbau, kambing, domba), cukup umur, dan tidak cacat. Unggas seperti ayam tidak sah untuk dijadikan hewan qurban.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-008',
    subject: 'Aqidah',
    topic: 'Iman Kepada Rasul-Rasul Allah',
    difficulty: 'Mudah',
    type: 'PG',
    stimulus: 'Para rasul Allah dibekali dengan sifat-sifat mulia yang wajib dimiliki untuk menyampaikan wahyu kepada umat manusia serta terbebas dari sifat mustahil.',
    question: 'Pasangan yang BENAR antara sifat wajib bagi rasul dan artinya adalah....',
    options: [
      { id: 'A', text: 'Siddiq artinya Cerdas dan Bijaksana' },
      { id: 'B', text: 'Amanah artinya Dapat Dipercaya' },
      { id: 'C', text: 'Tabligh artinya Berkata Benar dan Jujur' },
      { id: 'D', text: 'Fathanah artinya Menyampaikan Wahyu' },
    ],
    correctAnswers: ['B'],
    explanation: 'Sifat wajib rasul: Siddiq (Jujur/Benar), Amanah (Dapat Dipercaya), Tabligh (Menyampaikan), Fathanah (Cerdas). Jadi pasangan yang benar adalah Amanah = Dapat Dipercaya.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-009',
    subject: 'Akhlak',
    topic: 'Adab Menggunakan Media Sosial dalam Islam',
    difficulty: 'Sedang',
    type: 'PG',
    stimulus: 'Di era digital saat ini, arus informasi begitu deras di media sosial. Seringkali beredar berita sensasional yang belum terverifikasi kebenarannya (hoaks) yang dapat memicu perpecahan masyarakat.',
    question: 'Sikap seorang muslim yang berpedoman pada Q.S. Al-Hujurat ayat 6 ketika menerima kabar burung yang belum pasti kebenarannya adalah....',
    options: [
      { id: 'A', text: 'Langsung membagikan (share) ke grup WhatsApp agar teman-teman waspada' },
      { id: 'B', text: 'Melakukan tabayyun (memeriksa dan mengklarifikasi kebenaran sumber kabar)' },
      { id: 'C', text: 'Menambahkan opini pribadi agar berita terlihat semakin menarik dan viral' },
      { id: 'D', text: 'Mengabaikan sambil mencela pihak pembuat berita' },
    ],
    correctAnswers: ['B'],
    explanation: 'Q.S. Al-Hujurat: 6 memerintahkan: "Wahai orang-orang yang beriman! Jika seseorang yang fasik datang kepadamu membawa suatu berita, maka telitilah kebenarannya (fatabayyanu) agar kamu tidak mencelakakan suatu kaum karena ketidaktahuanmu".',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-010',
    subject: 'Sejarah Kebudayaan Islam',
    topic: 'Strategi Dakwah Walisongo di Pulau Jawa',
    difficulty: 'Sedang',
    type: 'PGK',
    stimulus: 'Penyebaran Islam di Nusantara oleh para Walisongo, khususnya di tanah Jawa dan wilayah Majapahit tempo dulu (termasuk kawasan Mojokerto), berhasil menarik simpati masyarakat karena mengedepankan pendekatan damai, akulturasi budaya, dan kearifan lokal.',
    question: 'Manakah bentuk dakwah Walisongo yang menggunakan pendekatan seni dan kebudayaan? (Pilih semua yang benar)',
    options: [
      { id: 'A', text: 'Pemanfaatan media wayang kulit dan tembang Ilir-Ilir oleh Sunan Kalijaga' },
      { id: 'B', text: 'Penciptaan tembang Dhandhanggula dan Sinom untuk menanamkan nilai tauhid' },
      { id: 'C', text: 'Pemaksaan hukum agama secara militer dan pembongkaran candi-candi leluhur' },
      { id: 'D', text: 'Tradisi Sekaten dan gamelan Kanjeng Kyai Guntur Madu oleh Sunan Bonang' },
    ],
    correctAnswers: ['A', 'B', 'D'],
    explanation: 'Walisongo berdakwah dengan arif melalui seni wayang, tembang macapat (Ilir-Ilir, Sinom), dan gamelan/sekaten tanpa kekerasan atau pemaksaan militer.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-011',
    subject: 'Fiqih',
    topic: 'Ketentuan Shalat Berjamaah dan Masbuq',
    difficulty: 'Sedang',
    type: 'BS',
    stimulus: 'Zaki adalah siswa SMP yang mengikuti shalat Zhuhur berjamaah di musholla sekolah. Karena terlambat datang, ketika Zaki bertakbiratul ihram dan takbir intiqal untuk rukuk, imam sedang berada pada posisi rukuk di rakaat kedua. Zaki sempat rukuk dengan thuma\'ninah bersama imam beberapa detik sebelum imam membaca tasmi\' (sami\'allahu liman hamidah) dan bangkit untuk i\'tidal.',
    question: 'Berdasarkan narasi peristiwa shalat masbuq Zaki di atas, tentukan nilai kebenaran dari masing-masing pernyataan berikut dengan memilih BENAR atau SALAH!',
    statements: [
      {
        id: 'S1',
        text: 'Zaki dihitung telah mendapatkan satu rakaat kedua bersama imam karena sempat rukuk thuma\'ninah sebelum imam bangkit i\'tidal.',
        correct: 'BENAR',
      },
      {
        id: 'S2',
        text: 'Zaki wajib langsung mengucap salam bersama imam pada rakaat keempat tanpa perlu berdiri menambah rakaat yang tertinggal.',
        correct: 'SALAH',
      },
      {
        id: 'S3',
        text: 'Zaki wajib berdiri kembali setelah imam selesai mengucap salam kedua untuk menyempurnakan 1 rakaat pertama yang terlewat.',
        correct: 'BENAR',
      },
      {
        id: 'S4',
        text: 'Ketinggalan satu rakaat membuat shalat berjamaah Zaki otomatis batal sehingga ia harus mengulang shalat sendiri dari awal.',
        correct: 'SALAH',
      },
    ],
    correctAnswers: ['S1:BENAR', 'S2:SALAH', 'S3:BENAR', 'S4:SALAH'],
    explanation: 'Makmum masbuq yang mendapati rukuk imam dengan thuma\'ninah terhitung mendapatkan rakaat tersebut. Setelah salam imam, masbuq wajib bangkit menambah rakaat yang tertinggal tanpa membatalkan shalatnya.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-012',
    subject: "Al-Qur'an Hadis",
    topic: 'Kandungan Q.S. Al-Anbiya Ayat 30 (Sains dan Al-Quran)',
    difficulty: 'Sedang',
    type: 'BS',
    stimulus: 'Dalam Q.S. Al-Anbiya\' [21]: 30, Allah Swt. berfirman:\n\nاَوَلَمْ يَرَ الَّذِيْنَ كَفَرُوْٓا اَنَّ السَّمٰوٰتِ وَالْاَرْضَ كَانَتَا رَتْقًا فَفَتَقْنٰهُمَاۗ وَجَعَلْنَا مِنَ الْمَاۤءِ كُلَّ شَيْءٍ حَيٍّۗ اَفَلَا يُؤْمِنُوْنَ\n\nAyat ini mengungkap bahwa langit dan bumi dahulunya adalah suatu kesatuan padu yang kemudian dipisahkan oleh Allah Swt., serta ditegaskan pula bahwa air dijadikan sebagai asal-mula seluruh kehidupan makhluk biologis di alam semesta.',
    question: 'Berdasarkan narasi dan pemahaman ayat tersebut, analisislah pernyataan berikut lalu tentukan apakah BENAR atau SALAH!',
    statements: [
      {
        id: 'S1',
        text: 'Al-Qur\'an menegaskan bahwa seluruh makhluk hidup diciptakan dan bergantung pada unsur air sebagai tanda kekuasaan Allah Swt.',
        correct: 'BENAR',
      },
      {
        id: 'S2',
        text: 'Ayat tersebut menjelaskan bahwa alam semesta langit dan bumi tercipta secara kebetulan tanpa ada Sang Maha Pencipta.',
        correct: 'SALAH',
      },
      {
        id: 'S3',
        text: 'Kesesuaian isyarat ilmiah Al-Qur\'an dengan sains modern membuktikan kebenaran wahyu Allah Swt. dan mukjizat kenabian Nabi Muhammad Saw.',
        correct: 'BENAR',
      },
    ],
    correctAnswers: ['S1:BENAR', 'S2:SALAH', 'S3:BENAR'],
    explanation: 'Q.S. Al-Anbiya: 30 membuktikan kemahakuasaan Allah dalam penciptaan alam semesta dan penciptaan makhluk hidup dari air, bukan kebetulan.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q-013',
    subject: 'Sejarah Kebudayaan Islam',
    topic: 'Jejak Peradaban Islam dan Makam Troloyo Mojokerto',
    difficulty: 'Sedang',
    type: 'BS',
    stimulus: 'Di Kecamatan Trowulan, Kabupaten Mojokerto, terdapat situs bersejarah Kompleks Makam Troloyo yang berasal dari era Kerajaan Majapahit (abad ke-14). Di kompleks makam ini dimakamkan tokoh-tokoh Muslim masa Majapahit, termasuk Syaikh Jumadil Kubro yang dikenal sebagai leluhur Walisongo. Hal ini membuktikan bahwa Islam telah bersemi dengan damai dan diakui di pusat ibukota Majapahit jauh sebelum runtuhnya kerajaan.',
    question: 'Perhatikan narasi sejarah Islam di Mojokerto tersebut, kemudian tentukan apakah masing-masing pernyataan berikut BENAR atau SALAH!',
    statements: [
      {
        id: 'S1',
        text: 'Kompleks Makam Troloyo di Trowulan membuktikan keberadaan komunitas Muslim terhormat di lingkungan Kerajaan Majapahit tempo dulu.',
        correct: 'BENAR',
      },
      {
        id: 'S2',
        text: 'Penyebaran Islam di wilayah Mojokerto masa Majapahit dilakukan melalui agresi militer berdarah dan penghancuran tempat ibadah leluhur.',
        correct: 'SALAH',
      },
      {
        id: 'S3',
        text: 'Syaikh Jumadil Kubro yang bermakam di Troloyo Mojokerto dihormati sebagai tokoh perintis dakwah Islam sebelum era Walisongo di tanah Jawa.',
        correct: 'BENAR',
      },
    ],
    correctAnswers: ['S1:BENAR', 'S2:SALAH', 'S3:BENAR'],
    explanation: 'Islam masuk dan berkembang di Majapahit secara damai melalui perdagangan dan keteladanan akhlak, sebagaimana dibuktikan oleh Makam Troloyo di Trowulan.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_EXAM: Exam = {
  id: 'exam-pai-mojokerto-2026',
  title: 'OLIMPIADE PAI SMP KABUPATEN MOJOKERTO 2026',
  description: 'Babak Penyisihan Computer Based Test (CBT) Olimpiade Pendidikan Agama Islam Jenjang SMP se-Kabupaten Mojokerto yang diselenggarakan oleh MGMP PAI Kabupaten Mojokerto.',
  questionCount: 10,
  pgCount: 5,
  pgkCount: 3,
  bsCount: 2,
  selectedQuestionIds: [
    'q-001', 'q-002', 'q-003', 'q-004', 'q-005',
    'q-006', 'q-007', 'q-008',
    'q-011', 'q-012',
  ],
  durationMinutes: 120,
  startAt: new Date(Date.now() - 3600000).toISOString(), // started 1 hour ago
  endAt: new Date(Date.now() + 86400000 * 7).toISOString(), // ends in 7 days
  randomQuestion: true,
  randomOption: true,
  antiCheat: true,
  fullscreenRequired: true,
  token: 'PAI2026',
  hideScoreFromParticipant: false,
  passingScore: 75,
  status: 'active',
  createdAt: new Date().toISOString(),
};

export const DEMO_ADMINS: AdminUser[] = [
  {
    uid: 'admin-mgmp-001',
    email: 'admin@mgmppai-mojokerto.sch.id',
    displayName: 'Admin MGMP PAI',
    role: 'admin',
  },
];
